name: moodle-stack
services:
  mariadb:
    image: docker.io/bitnamilegacy/mariadb:11.8.3-debian-12-r0
    platform: linux/arm64
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ../data/mariadb:/bitnami/mariadb
    networks: [moodle_net]

  moodle:
    image: docker.io/bitnamilegacy/moodle:4.4.4-debian-12-r4
    platform: linux/arm64
    restart: unless-stopped
    depends_on: [mariadb]
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=200M
      - PHP_POST_MAX_SIZE=200M
      - PHP_MEMORY_LIMIT=256M
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - BITNAMI_DEBUG=false
      - LANG=de_DE.UTF-8
      - LANGUAGE=de_DE.UTF-8
      - LC_ALL=de_DE.UTF-8
    ports:
      - "${MOODLE_HTTP_PORT}:8080"
      # - "8443:8443"
    volumes:
      - ../data/moodle:/bitnami/moodle
      - ../data/moodledata:/bitnami/moodledata
      - ../data/moodle-init:/docker-entrypoint-init.d
    networks: [moodle_net]

  proxy:
    build:
      context: ../proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MOODLE_URL=${MOODLE_URL}
      - MOODLE_TOKEN=${MOODLE_TOKEN}
      - OLLAMA_URL=${OLLAMA_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    ports:
      - "${PROXY_PORT}:3000"
    networks: [moodle_net]
    depends_on: [moodle]

networks:
  moodle_net:
    driver: bridge
