name: Deploy to Raspberry Pi

on:
    push:
        branches: [main]
    workflow_dispatch: # Allow manual triggering of the workflow

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Run deploy script
              run: |
                  cd /home/admin/moodle
                  bash deploy.sh
